<?php

// Data functions (insert, update, delete, form) for table trans_mrs2016

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function trans_mrs2016_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('trans_mrs2016');
	if(!$arrPerm[1]){
		return false;
	}

	$data['firstname'] = makeSafe($_REQUEST['firstname']);
		if($data['firstname'] == empty_lookup_value){ $data['firstname'] = ''; }
	$data['lastname'] = makeSafe($_REQUEST['lastname']);
		if($data['lastname'] == empty_lookup_value){ $data['lastname'] = ''; }
	$data['email'] = makeSafe($_REQUEST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['phone']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['quantity'] = makeSafe($_REQUEST['quantity']);
		if($data['quantity'] == empty_lookup_value){ $data['quantity'] = ''; }
	$data['amount'] = makeSafe($_REQUEST['amount']);
		if($data['amount'] == empty_lookup_value){ $data['amount'] = ''; }
	$data['mailinglist'] = makeSafe($_REQUEST['mailinglist']);
		if($data['mailinglist'] == empty_lookup_value){ $data['mailinglist'] = ''; }
	$data['remarks'] = br2nl(makeSafe($_REQUEST['remarks']));
	$data['transactiondate'] = parseCode('<%%creationDate%%>', true, true);
	$data['seller'] = parseCode('<%%creatorUsername%%>', true);
	$data['editingdate'] = parseMySQLDate('', '<%%editingDate%%>');

	// hook: trans_mrs2016_before_insert
	if(function_exists('trans_mrs2016_before_insert')){
		$args=array();
		if(!trans_mrs2016_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `trans_mrs2016` set       `firstname`=' . (($data['firstname'] !== '' && $data['firstname'] !== NULL) ? "'{$data['firstname']}'" : 'NULL') . ', `lastname`=' . (($data['lastname'] !== '' && $data['lastname'] !== NULL) ? "'{$data['lastname']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `quantity`=' . (($data['quantity'] !== '' && $data['quantity'] !== NULL) ? "'{$data['quantity']}'" : 'NULL') . ', `amount`=' . (($data['amount'] !== '' && $data['amount'] !== NULL) ? "'{$data['amount']}'" : 'NULL') . ', `mailinglist`=' . (($data['mailinglist'] !== '' && $data['mailinglist'] !== NULL) ? "'{$data['mailinglist']}'" : 'NULL') . ', `remarks`=' . (($data['remarks'] !== '' && $data['remarks'] !== NULL) ? "'{$data['remarks']}'" : 'NULL') . ', `transactiondate`=' . "'{$data['transactiondate']}'" . ', `seller`=' . "'{$data['seller']}'" . ', `editingdate`=' . (($data['editingdate'] != '') ? "'{$data['editingdate']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"trans_mrs2016_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: trans_mrs2016_after_insert
	if(function_exists('trans_mrs2016_after_insert')){
		$res = sql("select * from `trans_mrs2016` where `transaction_id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!trans_mrs2016_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='trans_mrs2016', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function trans_mrs2016_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('trans_mrs2016');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='trans_mrs2016' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='trans_mrs2016' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: trans_mrs2016_before_delete
	if(function_exists('trans_mrs2016_before_delete')){
		$args=array();
		if(!trans_mrs2016_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: duck_mrs2016
	$res = sql("select `transaction_id` from `trans_mrs2016` where `transaction_id`='$selected_id'", $eo);
	$transaction_id = db_fetch_row($res);
	$rires = sql("select count(1) from `duck_mrs2016` where `transaction_id`='".addslashes($transaction_id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "duck_mrs2016", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "duck_mrs2016", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='trans_mrs2016_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='trans_mrs2016_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `trans_mrs2016` where `transaction_id`='$selected_id'", $eo);

	// hook: trans_mrs2016_after_delete
	if(function_exists('trans_mrs2016_after_delete')){
		$args=array();
		trans_mrs2016_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='trans_mrs2016' and pkValue='$selected_id'", $eo);
}

function trans_mrs2016_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('trans_mrs2016');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='trans_mrs2016' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='trans_mrs2016' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['firstname'] = makeSafe($_REQUEST['firstname']);
		if($data['firstname'] == empty_lookup_value){ $data['firstname'] = ''; }
	$data['lastname'] = makeSafe($_REQUEST['lastname']);
		if($data['lastname'] == empty_lookup_value){ $data['lastname'] = ''; }
	$data['email'] = makeSafe($_REQUEST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['phone']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['quantity'] = makeSafe($_REQUEST['quantity']);
		if($data['quantity'] == empty_lookup_value){ $data['quantity'] = ''; }
	$data['amount'] = makeSafe($_REQUEST['amount']);
		if($data['amount'] == empty_lookup_value){ $data['amount'] = ''; }
	$data['mailinglist'] = makeSafe($_REQUEST['mailinglist']);
		if($data['mailinglist'] == empty_lookup_value){ $data['mailinglist'] = ''; }
	$data['remarks'] = br2nl(makeSafe($_REQUEST['remarks']));
	$data['transactiondate'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['editingdate'] = parseCode('<%%editingDate%%>', false, true);
	$data['editor'] = parseCode('<%%editorUsername%%>', false);
	$data['selectedID']=makeSafe($selected_id);

	// hook: trans_mrs2016_before_update
	if(function_exists('trans_mrs2016_before_update')){
		$args=array();
		if(!trans_mrs2016_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `trans_mrs2016` set       `firstname`=' . (($data['firstname'] !== '' && $data['firstname'] !== NULL) ? "'{$data['firstname']}'" : 'NULL') . ', `lastname`=' . (($data['lastname'] !== '' && $data['lastname'] !== NULL) ? "'{$data['lastname']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `quantity`=' . (($data['quantity'] !== '' && $data['quantity'] !== NULL) ? "'{$data['quantity']}'" : 'NULL') . ', `amount`=' . (($data['amount'] !== '' && $data['amount'] !== NULL) ? "'{$data['amount']}'" : 'NULL') . ', `mailinglist`=' . (($data['mailinglist'] !== '' && $data['mailinglist'] !== NULL) ? "'{$data['mailinglist']}'" : 'NULL') . ', `remarks`=' . (($data['remarks'] !== '' && $data['remarks'] !== NULL) ? "'{$data['remarks']}'" : 'NULL') . ', `transactiondate`=`transactiondate`' . ', `editingdate`=' . "'{$data['editingdate']}'" . ', `editor`=' . "'{$data['editor']}'" . " where `transaction_id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="trans_mrs2016_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: trans_mrs2016_after_update
	if(function_exists('trans_mrs2016_after_update')){
		$res = sql("SELECT * FROM `trans_mrs2016` WHERE `transaction_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['transaction_id'];
		$args = array();
		if(!trans_mrs2016_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='trans_mrs2016' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function trans_mrs2016_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('trans_mrs2016');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: transactiondate
	$combo_transactiondate = new DateCombo;
	$combo_transactiondate->DateFormat = "dmy";
	$combo_transactiondate->MinYear = 1900;
	$combo_transactiondate->MaxYear = 2100;
	$combo_transactiondate->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_transactiondate->MonthNames = $Translation['month names'];
	$combo_transactiondate->NamePrefix = 'transactiondate';
	// combobox: editingdate
	$combo_editingdate = new DateCombo;
	$combo_editingdate->DateFormat = "dmy";
	$combo_editingdate->MinYear = 1900;
	$combo_editingdate->MaxYear = 2100;
	$combo_editingdate->DefaultDate = parseMySQLDate('<%%editingDate%%>', '<%%editingDate%%>');
	$combo_editingdate->MonthNames = $Translation['month names'];
	$combo_editingdate->NamePrefix = 'editingdate';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='trans_mrs2016' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='trans_mrs2016' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `trans_mrs2016` where `transaction_id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_transactiondate->DefaultDate = $row['transactiondate'];
		$combo_editingdate->DefaultDate = $row['editingdate'];
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/trans_mrs2016_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/trans_mrs2016_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Badeendrace 2015 details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return trans_mrs2016_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return trans_mrs2016_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return trans_mrs2016_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#firstname').replaceWith('<div class=\"form-control-static\" id=\"firstname\">' + (jQuery('#firstname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#lastname').replaceWith('<div class=\"form-control-static\" id=\"lastname\">' + (jQuery('#lastname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#phone').replaceWith('<div class=\"form-control-static\" id=\"phone\">' + (jQuery('#phone').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#quantity').replaceWith('<div class=\"form-control-static\" id=\"quantity\">' + (jQuery('#quantity').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#amount').replaceWith('<div class=\"form-control-static\" id=\"amount\">' + (jQuery('#amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#mailinglist').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#remarks').replaceWith('<div class=\"form-control-static\" id=\"remarks\">' + (jQuery('#remarks').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(transactiondate)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_transactiondate->GetHTML(true) . '</div>' : $combo_transactiondate->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(transactiondate)%%>', $combo_transactiondate->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(editingdate)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_editingdate->GetHTML(true) . '</div>' : $combo_editingdate->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(editingdate)%%>', $combo_editingdate->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'iso-8859-1') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'iso-8859-1') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(transaction_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(firstname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(lastname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(phone)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(quantity)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(amount)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(mailinglist)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(remarks)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(transactiondate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(seller)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(editingdate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(editor)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(transaction_id)%%>', htmlspecialchars($row['transaction_id'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transaction_id)%%>', urlencode($urow['transaction_id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(firstname)%%>', htmlspecialchars($row['firstname'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(firstname)%%>', urlencode($urow['firstname']), $templateCode);
		$templateCode=str_replace('<%%VALUE(lastname)%%>', htmlspecialchars($row['lastname'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(lastname)%%>', urlencode($urow['lastname']), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', htmlspecialchars($row['email'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		$templateCode=str_replace('<%%VALUE(phone)%%>', htmlspecialchars($row['phone'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(phone)%%>', urlencode($urow['phone']), $templateCode);
		$templateCode=str_replace('<%%VALUE(quantity)%%>', htmlspecialchars($row['quantity'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(quantity)%%>', urlencode($urow['quantity']), $templateCode);
		$templateCode=str_replace('<%%VALUE(amount)%%>', htmlspecialchars($row['amount'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(amount)%%>', urlencode($urow['amount']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(mailinglist)%%>', ($row['mailinglist'] ? "checked" : ""), $templateCode);
		if($dvprint){
			$templateCode = str_replace('<%%VALUE(remarks)%%>', nl2br(htmlspecialchars($row['remarks'], ENT_QUOTES, 'iso-8859-1')), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(remarks)%%>', htmlspecialchars($row['remarks'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		}
		$templateCode=str_replace('<%%URLVALUE(remarks)%%>', urlencode($urow['remarks']), $templateCode);
		$templateCode=str_replace('<%%VALUE(transactiondate)%%>', @date('d-m-Y', @strtotime(htmlspecialchars($row['transactiondate'], ENT_QUOTES, 'iso-8859-1'))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transactiondate)%%>', urlencode(@date('d-m-Y', @strtotime(htmlspecialchars($urow['transactiondate'], ENT_QUOTES, 'iso-8859-1')))), $templateCode);
		$templateCode=str_replace('<%%VALUE(seller)%%>', htmlspecialchars($row['seller'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(seller)%%>', urlencode($urow['seller']), $templateCode);
		$templateCode=str_replace('<%%VALUE(editingdate)%%>', @date('d-m-Y', @strtotime(htmlspecialchars($row['editingdate'], ENT_QUOTES, 'iso-8859-1'))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(editingdate)%%>', urlencode(@date('d-m-Y', @strtotime(htmlspecialchars($urow['editingdate'], ENT_QUOTES, 'iso-8859-1')))), $templateCode);
		$templateCode=str_replace('<%%VALUE(editor)%%>', htmlspecialchars($row['editor'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(editor)%%>', urlencode($urow['editor']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(transaction_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transaction_id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(firstname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(firstname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(lastname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(lastname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(phone)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(phone)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(quantity)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(quantity)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(amount)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(amount)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(mailinglist)%%>', 'checked', $templateCode);
		$templateCode=str_replace('<%%VALUE(remarks)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(remarks)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(transactiondate)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transactiondate)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(seller)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(seller)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(editingdate)%%>', '<%%editingDate%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(editingdate)%%>', urlencode('<%%editingDate%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(editor)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(editor)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: trans_mrs2016_dv
	if(function_exists('trans_mrs2016_dv')){
		$args=array();
		trans_mrs2016_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>