<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/trans_mrs2016.php");
	include("$currDir/trans_mrs2016_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('trans_mrs2016');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "trans_mrs2016";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`trans_mrs2016`.`transaction_id`" => "transaction_id",
		"`trans_mrs2016`.`firstname`" => "firstname",
		"`trans_mrs2016`.`lastname`" => "lastname",
		"`trans_mrs2016`.`email`" => "email",
		"`trans_mrs2016`.`phone`" => "phone",
		"`trans_mrs2016`.`quantity`" => "quantity",
		"`trans_mrs2016`.`amount`" => "amount",
		"concat('<img src=\"', if(`trans_mrs2016`.`mailinglist`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "mailinglist",
		"`trans_mrs2016`.`remarks`" => "remarks",
		"if(`trans_mrs2016`.`transactiondate`,date_format(`trans_mrs2016`.`transactiondate`,'%d-%m-%Y'),'')" => "transactiondate",
		"`trans_mrs2016`.`seller`" => "seller",
		"if(`trans_mrs2016`.`editingdate`,date_format(`trans_mrs2016`.`editingdate`,'%d-%m-%Y'),'')" => "editingdate",
		"`trans_mrs2016`.`editor`" => "editor"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`trans_mrs2016`.`transaction_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`trans_mrs2016`.`quantity`',
		7 => '`trans_mrs2016`.`amount`',
		8 => '`trans_mrs2016`.`mailinglist`',
		9 => 9,
		10 => '`trans_mrs2016`.`transactiondate`',
		11 => 11,
		12 => '`trans_mrs2016`.`editingdate`',
		13 => 13
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`trans_mrs2016`.`transaction_id`" => "transaction_id",
		"`trans_mrs2016`.`firstname`" => "firstname",
		"`trans_mrs2016`.`lastname`" => "lastname",
		"`trans_mrs2016`.`email`" => "email",
		"`trans_mrs2016`.`phone`" => "phone",
		"`trans_mrs2016`.`quantity`" => "quantity",
		"`trans_mrs2016`.`amount`" => "amount",
		"`trans_mrs2016`.`mailinglist`" => "mailinglist",
		"`trans_mrs2016`.`remarks`" => "remarks",
		"if(`trans_mrs2016`.`transactiondate`,date_format(`trans_mrs2016`.`transactiondate`,'%d-%m-%Y'),'')" => "transactiondate",
		"`trans_mrs2016`.`seller`" => "seller",
		"if(`trans_mrs2016`.`editingdate`,date_format(`trans_mrs2016`.`editingdate`,'%d-%m-%Y'),'')" => "editingdate",
		"`trans_mrs2016`.`editor`" => "editor"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`trans_mrs2016`.`transaction_id`" => "Transactie nr",
		"`trans_mrs2016`.`firstname`" => "Voornaam",
		"`trans_mrs2016`.`lastname`" => "Achternaam",
		"`trans_mrs2016`.`email`" => "Email",
		"`trans_mrs2016`.`phone`" => "Telefoon",
		"`trans_mrs2016`.`quantity`" => "Aantal",
		"`trans_mrs2016`.`amount`" => "Bedrag",
		"`trans_mrs2016`.`mailinglist`" => "Mailinglijst",
		"`trans_mrs2016`.`remarks`" => "Opmerkingen",
		"`trans_mrs2016`.`transactiondate`" => "Verkoopdatum",
		"`trans_mrs2016`.`seller`" => "Verkoper",
		"`trans_mrs2016`.`editingdate`" => "Mutatiedatum",
		"`trans_mrs2016`.`editor`" => "Aanpasser"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`trans_mrs2016`.`transaction_id`" => "transaction_id",
		"`trans_mrs2016`.`firstname`" => "firstname",
		"`trans_mrs2016`.`lastname`" => "lastname",
		"`trans_mrs2016`.`email`" => "email",
		"`trans_mrs2016`.`phone`" => "phone",
		"`trans_mrs2016`.`quantity`" => "quantity",
		"`trans_mrs2016`.`amount`" => "amount",
		"concat('<img src=\"', if(`trans_mrs2016`.`mailinglist`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "mailinglist",
		"`trans_mrs2016`.`remarks`" => "remarks",
		"if(`trans_mrs2016`.`transactiondate`,date_format(`trans_mrs2016`.`transactiondate`,'%d-%m-%Y'),'')" => "transactiondate",
		"`trans_mrs2016`.`seller`" => "seller",
		"if(`trans_mrs2016`.`editingdate`,date_format(`trans_mrs2016`.`editingdate`,'%d-%m-%Y'),'')" => "editingdate",
		"`trans_mrs2016`.`editor`" => "editor"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`trans_mrs2016` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 22;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "trans_mrs2016_view.php";
	$x->RedirectAfterInsert = "trans_mrs2016_view.php?SelectedID=#ID#";
	$x->TableTitle = "Verkoop badeendrace 2016";
	$x->TableIcon = "resources/table_icons/anchor.png";
	$x->PrimaryKey = "`trans_mrs2016`.`transaction_id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 100, 150, 100, 150, 75, 75);
	$x->ColCaption = array("Transactie nr", "Voornaam", "Achternaam", "Email", "Telefoon", "Aantal", "Bedrag", "Mailinglijst", "Verkoopdatum", "Verkoper");
	$x->ColFieldName = array('transaction_id', 'firstname', 'lastname', 'email', 'phone', 'quantity', 'amount', 'mailinglist', 'transactiondate', 'seller');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 10, 11);

	$x->Template = 'templates/trans_mrs2016_templateTV.html';
	$x->SelectedTemplate = 'templates/trans_mrs2016_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `trans_mrs2016`.`transaction_id`=membership_userrecords.pkValue and membership_userrecords.tableName='trans_mrs2016' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `trans_mrs2016`.`transaction_id`=membership_userrecords.pkValue and membership_userrecords.tableName='trans_mrs2016' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`trans_mrs2016`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: trans_mrs2016_init
	$render=TRUE;
	if(function_exists('trans_mrs2016_init')){
		$args=array();
		$render=trans_mrs2016_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: trans_mrs2016_header
	$headerCode='';
	if(function_exists('trans_mrs2016_header')){
		$args=array();
		$headerCode=trans_mrs2016_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: trans_mrs2016_footer
	$footerCode='';
	if(function_exists('trans_mrs2016_footer')){
		$args=array();
		$footerCode=trans_mrs2016_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>